name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Build jar file
        run: mvn package
      - name: Deploy - Publish Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: javadoc
          project: maven
      - name: Maven Version Bump Action
        uses: nnichols/maven-version-bump-action@v4
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven Jar Publish
        uses: eric2788/maven-jar-publish@v2
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          java-version: 11
          locate: .
          upload-module: .
